## Day Objectivies
###  Functional programming
### list comprehension
### Iterators and generator
### Maps
### Filter
### Lambda

In [2]:
### list cmprehension
### while comparing with for loop with works more efficient
### to reduce the lines of code
### program using comprehension
n=10
li=[]
for i in  range (1,n+1):
    li.append(i)
print(li)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [4]:
li=[i for i in range(1,11)]
li

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [5]:
li=[i**3 for i in li]
li

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [7]:
k=[10,20,5,2]
k=[i**2 for i in k]
k

[100, 400, 25, 4]

In [8]:
st=1970
et=2020
leapyear=[i for i in range(st,et+1)
         if(i%400)==0 or (i%100!=0 and i%4==0)]
leapyear

[1972, 1976, 1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020]

In [10]:
st=1940
et=2010
leapyear=[i for i in range(st,et+1)
         if(i%400)==0 or (i%100!=0 and i%4==0)]
leapyear

[1940,
 1944,
 1948,
 1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008]

In [25]:
def cummlativesum(n):
    s=0
    li=[]
    for i in range(1,n+1):
        s=s+i
        print(s)
        li.append(s)
    print(li)
cummlativesum(4)

1
3
6
10
[1, 3, 6, 10]


In [13]:
def cummlativemultiplication(n):
    multiplication=1
    li=[]
    for i in range(1,n+1):
        multiplication=multiplication*i
        print(multiplication)
        li.append(multiplication)
    print(li)
cummlativemultiplication(4)

1
2
6
24
[1, 2, 6, 24]


In [30]:
n=6
cummlativesum = [sum(range(1,i+1)) for i in range(1,n+1)]
cummlativesum

TypeError: 'int' object is not callable

In [ ]:
# Iterators 
### iterator is in object that contains no.of elements
## 2 methods
## iter()
##  next()
##   all ds are iterable objects

In [40]:
it = "python"
it=iter('python')
print(it)
next(it)

'p'

In [41]:
print(next(it))

y


In [50]:
next(it)

TypeError: 'str' object is not an iterator

In [42]:
it="python"
for i in it:
    print(i)

p
y
t
h
o
n


In [46]:
a='pythonprogram'
a=iter('pythonprogram')
a

In [47]:
next(a)

'p'

In [48]:
next(a)

'y'

In [55]:
print('1:')
print(next(a))

1:
o


In [56]:
course=["c","c++","python"]
result=iter(course)
print(next(result))
print(next(result))
print(next(result))

c
c++
python


In [58]:
btechcourse=["it","cse","eee","mech"]
result=iter(btechcourse)
print(next(result))
print(next(result))
print(next(result))
print(next(result))

it
cse
eee
mech


In [ ]:
### geneators
## is nothing but a fun
## we can iter using generators
## yield is keyword to return values
### generator will to yield  to a function

In [65]:
def generatorfunction():
    yield 4
    yield 5
    yield 6
generatorfunction()
for value in generatorfunction():
    print(value)

4
5
6


In [67]:
def gen():
    n=2
    while True:
        n**=2
        yield n
a=gen()
for i in range(5):
    print(next(a))

4
16
256
65536
4294967296


In [70]:
def gen():
    n=3
    while True:
        n**=3
        yield n
a=gen()
for i in range(5):
    print(next(a))

27
19683
7625597484987
443426488243037769948249630619149892803
87189642485960958202911070585860771696964072404731750085525219437990967093723439943475549906831683116791055225665627


# MAPS in python

## it produces a list of results that it apply given function to each item of a given iterable (list,tuples,sets etc..)

### syntax: map(functioniterable)

In [75]:
def addition(n):
    return n+n
result=list(map(addition,range(1,5)))
print(result)

[2, 4, 6, 8]


In [80]:
def multiplication(k):
    return k*2
result=list(map(multiplication,range(1,10)))
print(result)

[2, 4, 6, 8, 10, 12, 14, 16, 18]


In [81]:
def squareofnumb(n):
    return n*n
result=set(map(squareofnumb,range(1,5)))
print(result)

{16, 1, 4, 9}


In [82]:
def squareofnumb(n):
    return n*n
result=tuple(map(squareofnumb,range(1,5)))
print(result)

(1, 4, 9, 16)


# Filters in python


- used to check whether the given element is boolean or not
- this method filters the given iterable,test each element is true or false and returns the element which is true

# syntax
- f:x->{T<F}


In [88]:
li=[1,2,'a','b','c',3]
def isalpha(c):
    c=str(c)
    if c.isalpha():
        return True
    return False
isalpha('a')
list(filter(isalpha,li))

['a', 'b', 'c']

In [89]:
li=[1,2,'a','b','c',3]
def isdigit(c):
    c=str(c)
    if c.isdigit():
        return True
    return False
isdigit('a')
list(filter(isdigit,li))

[1, 2, 3]

# Numpy(numericalpython)


- Numpy is a python libary and fundmental package for scientific computing in python

- It  used to create multidimensional arrays for fast operations

- use the following import conversionto acess numpy libary
- import numpy as np
- Numpy have a fixed size of arrays used to store  a collection of elments,unlike python lists

In [9]:
## creating 1D using numpy as np
import numpy as np
array_1d=np.array([2,4,5,6,7,9])
print(array_1d)
type(array_1d)

[2 4 5 6 7 9]


numpy.ndarray

In [7]:
### creating 2d array using numpy
import numpy as np
array_2d=np.array([[2,4,5,6,7],[5,10,4,7,8]])
print(array_2d)

[[ 2  4  5  6  7]
 [ 5 10  4  7  8]]


In [8]:
### creating  3d array using numpy
import numpy as np
array_3d=np.array([[1,3,5,6],[1,5,6,7],[7,8,9,10],[11,41,48,52,],[4,8,9,7],[4,7,9,8]])
print(array_3d)

[[ 1  3  5  6]
 [ 1  5  6  7]
 [ 7  8  9 10]
 [11 41 48 52]
 [ 4  8  9  7]
 [ 4  7  9  8]]


In [14]:
# program to print the given list in to an array
import numpy as np
li=[1,2,3,'z']
a=np.array([li])
a

array([['1', '2', '3', 'z']], dtype='<U11')

- If the size of the array is large to type, we can simply use array range called "arange"

In [16]:
# example 
# To print 1d array between 1 to 15
import numpy as np
a=np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [17]:
import numpy as np
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Creating array using arange and reshape function .If the array size is too large,then Numpy will kips the middle numbers for given range.for example print 1000 numbers in a 1D array.

In [19]:
import numpy as np
a2=np.arange(10000)
a2

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [21]:
a2=np.arange(10000).reshape(100,100)
print(a2)

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [25]:
a2=np.arange(100).reshape(2,50)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [27]:
a2=np.arange(40).reshape(2,20)
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [28]:
np.full((3,3),2)


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [31]:
np.full((3,3),2.2,dtype=np.int)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [32]:
np.full((3,3),2.2)

array([[2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2]])

In [33]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [40]:
import numpy as np
x=np.zeros((3,2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [43]:
f=np.array([1,2,3])

In [44]:
f

array([1, 2, 3])

In [45]:
np.tile(f,(3,1))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [50]:
50*np.random.random()*2

15.525899085444394

In [51]:
np.random.random([3,3])

array([[0.56300613, 0.82327981, 0.12553348],
       [0.02184854, 0.7271826 , 0.70667288],
       [0.57289662, 0.04613424, 0.19288582]])

In [66]:
a=np.linspace(1,10,100)

In [67]:
a

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

# PANDAS
- pandas bascialy use for data analysis.it is build on top of numpy only
- we will mostly be using this pandas package a lot
- in fact if you are going to use it heavily for any data manipulation,any sort of data analysis and any sort of datavisualization and any sort of machine learning model building ##### datavisualisation


In [68]:
import pandas as pd
a=pd.Series([1,2,3,4,5])
a

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [71]:
a[3]


4

In [73]:
type(a)

pandas.core.series.Series

In [83]:
a=pd.Series(['a','b','c',11])
a

0     a
1     b
2     c
3    11
dtype: object

In [78]:
a=pd.date_range(start ='08-1-2019',end='20-8-2019')
a

DatetimeIndex(['2019-08-01', '2019-08-02', '2019-08-03', '2019-08-04',
               '2019-08-05', '2019-08-06', '2019-08-07', '2019-08-08',
               '2019-08-09', '2019-08-10', '2019-08-11', '2019-08-12',
               '2019-08-13', '2019-08-14', '2019-08-15', '2019-08-16',
               '2019-08-17', '2019-08-18', '2019-08-19', '2019-08-20'],
              dtype='datetime64[ns]', freq='D')

# Pandas DataFrame
- Dataframe is just like a table.which is going to contain rows and column
- Row can have a index
- Column can have a meaning full names



In [91]:
import numpy as np
temp=np.random.randint(low=20,high=100,size=[20])
name=np.random.choice(['harsha','harshi','sri','harshasri'],20)
av=np.random.choice([10,12,13,14,50],20)
a=list(zip(temp,name,av))
df=pd.DataFrame(data=a,columns=['temp','name','av'])
df

temp       name  av
0     24     harsha  13
1     94        sri  50
2     20        sri  13
3     72     harshi  50
4     86     harshi  13
5     62        sri  12
6     33     harshi  10
7     59     harshi  12
8     26        sri  13
9     74        sri  13
10    80     harshi  12
11    89  harshasri  50
12    78     harshi  10
13    20     harsha  10
14    72        sri  12
15    87     harsha  12
16    27     harsha  50
17    45     harsha  50
18    99        sri  50
19    33        sri  50

In [85]:
temp=np.random.randint(low=20,high=100,size=[20])
temp

array([50, 35, 35, 89, 67, 54, 56, 77, 27, 87, 64, 82, 41, 96, 45, 74, 74,
       67, 30, 43])

In [86]:
name=np.random.choice(['ravi','kishore','anil','kumar'],20)
name

array(['ravi', 'kumar', 'ravi', 'ravi', 'anil', 'kumar', 'anil',
       'kishore', 'kumar', 'anil', 'anil', 'ravi', 'kumar', 'anil',
       'kumar', 'kishore', 'kumar', 'kumar', 'anil', 'kishore'],
      dtype='<U7')

In [87]:
av=np.random.choice([10,12,13,14,50],20)
av

array([14, 50, 12, 12, 10, 12, 13, 12, 12, 12, 13, 13, 14, 50, 14, 14, 13,
       10, 50, 50])

In [92]:
a=list(zip(temp,name,av))
a

[(24, 'harsha', 13),
 (94, 'sri', 50),
 (20, 'sri', 13),
 (72, 'harshi', 50),
 (86, 'harshi', 13),
 (62, 'sri', 12),
 (33, 'harshi', 10),
 (59, 'harshi', 12),
 (26, 'sri', 13),
 (74, 'sri', 13),
 (80, 'harshi', 12),
 (89, 'harshasri', 50),
 (78, 'harshi', 10),
 (20, 'harsha', 10),
 (72, 'sri', 12),
 (87, 'harsha', 12),
 (27, 'harsha', 50),
 (45, 'harsha', 50),
 (99, 'sri', 50),
 (33, 'sri', 50)]

In [93]:
df=pd.DataFrame(data=a,columns=['temp','name','av'])
df

temp       name  av
0     24     harsha  13
1     94        sri  50
2     20        sri  13
3     72     harshi  50
4     86     harshi  13
5     62        sri  12
6     33     harshi  10
7     59     harshi  12
8     26        sri  13
9     74        sri  13
10    80     harshi  12
11    89  harshasri  50
12    78     harshi  10
13    20     harsha  10
14    72        sri  12
15    87     harsha  12
16    27     harsha  50
17    45     harsha  50
18    99        sri  50
19    33        sri  50

In [94]:
df.head()

temp    name  av
0    24  harsha  13
1    94     sri  50
2    20     sri  13
3    72  harshi  50
4    86  harshi  13

In [95]:
df.tail()

temp    name  av
15    87  harsha  12
16    27  harsha  50
17    45  harsha  50
18    99     sri  50
19    33     sri  50

In [96]:
type(df)

pandas.core.frame.DataFrame

In [97]:
df.shape

(20, 3)

In [98]:
df.columns

Index(['temp', 'name', 'av'], dtype='object')

In [99]:
df.name

0        harsha
1           sri
2           sri
3        harshi
4        harshi
5           sri
6        harshi
7        harshi
8           sri
9           sri
10       harshi
11    harshasri
12       harshi
13       harsha
14          sri
15       harsha
16       harsha
17       harsha
18          sri
19          sri
Name: name, dtype: object

In [100]:
df['name']

0        harsha
1           sri
2           sri
3        harshi
4        harshi
5           sri
6        harshi
7        harshi
8           sri
9           sri
10       harshi
11    harshasri
12       harshi
13       harsha
14          sri
15       harsha
16       harsha
17       harsha
18          sri
19          sri
Name: name, dtype: object

In [102]:
df['temp'].describe()

count    20.00000
mean     59.00000
std      27.66339
min      20.00000
25%      31.50000
50%      67.00000
75%      81.50000
max      99.00000
Name: temp, dtype: float64

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
temp    20 non-null int64
name    20 non-null object
av      20 non-null int64
dtypes: int64(2), object(1)
memory usage: 560.0+ bytes


In [105]:
df.values

array([[24, 'harsha', 13],
       [94, 'sri', 50],
       [20, 'sri', 13],
       [72, 'harshi', 50],
       [86, 'harshi', 13],
       [62, 'sri', 12],
       [33, 'harshi', 10],
       [59, 'harshi', 12],
       [26, 'sri', 13],
       [74, 'sri', 13],
       [80, 'harshi', 12],
       [89, 'harshasri', 50],
       [78, 'harshi', 10],
       [20, 'harsha', 10],
       [72, 'sri', 12],
       [87, 'harsha', 12],
       [27, 'harsha', 50],
       [45, 'harsha', 50],
       [99, 'sri', 50],
       [33, 'sri', 50]], dtype=object)

In [107]:
import numpy as np
marks=np.random.randint(low=20,high=100,size=[5])
name=np.random.choice(['ramya','harsha','anu','priya'],5)
av=np.random.choice([10,12,13,14,50],5)
a=list(zip(marks,name,av))
df=pd.DataFrame(data=a,columns=['marks','name','av'])
df

marks    name  av
0     72     anu  13
1     92  harsha  12
2     68   ramya  13
3     92   ramya  14
4     54     anu  12

In [ ]:
import turtle as t
wn=turtle.screen()
t1-t.turtle()
t1.foward(90)
